import background from './res/img_background.jpg'
import icon from './res/icon.png'
import coo from './res/coo.jpeg'
import cio from './res/cio.jpg'
import ceo from './res/ceo_blair.jpg'
import cto from './res/cto.jpg'
import cco from './res/cco.jpg'
import git from './res/git.png'
import vegetables from './res/vegetables.png'
import fruits from './res/fruits.png'
import beverages from './res/beverages.png'
import liveTreesAndPlants from './res/live_plants.jpeg'
import animalProducts from './res/animal_products.jpeg'
import goal from './res/aim.svg'
import mission from './res/mission.png'
import target from './res/target.png'
import location from './res/location.png'
import availability from './res/availability.png'
import year from './res/year.png'
import sponsor from './res/sponsor.png'
import licence from './res/licence.png'
import facebook from './res/facebook.png'
import linkedin from './res/in.png'
import instagram from './res/instagram.png'
import feedback from './res/mail.png'
import records from './res/mail.png'
import forms from './res/mail.png'
import departments from './res/mail.png'
import mail from './res/mail.png'

const Resources = { background, icon, coo, cio, ceo, cto, cco, git, vegetables, fruits, beverages, liveTreesAndPlants, animalProducts, goal, mission, target, location, availability, year, sponsor, licence, facebook, linkedin, instagram, mail }

export default Resources

